condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_block_trailing_comma = true
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
wrap_comments = true
